// Generated by CoffeeScript 1.6.2
(function() {
  var JSOG, assert, decoded, encoded, inside, outside;

  assert = require('assert');

  JSOG = require('../JSOG');

  inside = {
    name: 'thing'
  };

  outside = {
    inside1: inside,
    inside2: inside
  };

  encoded = JSOG.encode(outside);

  describe('no id should be set', function() {
    it('should not have added an id to outside', function() {
      return assert(!(outside['$id'] != null));
    });
    return it('should not have added an id to inside', function() {
      return assert(!(inside['$id'] != null));
    });
  });

  decoded = JSOG.decode(encoded);

  console.log("Decoded is:");

  console.log(JSON.stringify(decoded, void 0, 4));

}).call(this);
