// Generated by CoffeeScript 1.6.2
(function() {
  var JSOG, encoded, inside, outside;

  JSOG = require('JSOG');

  inside = {
    name: 'thing'
  };

  outside = {
    inside1: inside,
    inside2: inside
  };

  encoded = JSOG.encode(outside);

  console.log(JSON.stringify(encoded));

}).call(this);
