// Generated by CoffeeScript 1.6.2
(function() {
  var JSOG, nextId, stripIds;

  JSOG = {};

  nextId = 1;

  stripIds = function(obj) {
    var key, val, _i, _len, _results, _results1;

    if (Array.isArray(obj)) {
      _results = [];
      for (_i = 0, _len = obj.length; _i < _len; _i++) {
        val = obj[_i];
        _results.push(stripIds(val));
      }
      return _results;
    } else if (typeof obj === 'object') {
      delete obj['@id'];
      _results1 = [];
      for (key in obj) {
        val = obj[key];
        _results1.push(stripIds(val));
      }
      return _results1;
    }
  };

  JSOG.encode = function(original) {
    var doEncode, result;

    doEncode = function(original) {
      var encodeArray, encodeObject;

      encodeObject = function(original) {
        var id, key, result, value;

        id = original['@id'];
        if (id != null) {
          return {
            '@ref': id
          };
        }
        result = {};
        original['@id'] = "" + (nextId++);
        for (key in original) {
          value = original[key];
          result[key] = doEncode(value);
        }
        return result;
      };
      encodeArray = function(original) {
        var val;

        return (function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = original.length; _i < _len; _i++) {
            val = original[_i];
            _results.push(encode(val));
          }
          return _results;
        })();
      };
      if (Array.isArray(original)) {
        return encodeArray(original);
      } else if (typeof original === 'object') {
        return encodeObject(original);
      } else {
        return original;
      }
    };
    result = doEncode(original);
    stripIds(original);
    return result;
  };

  JSOG.decode = function(encoded) {
    var doDecode, found;

    found = {};
    doDecode = function(encoded) {
      var decodeArray, decodeObject;

      decodeObject = function(encoded) {
        var id, key, ref, result, value;

        ref = encoded['@ref'];
        if (ref != null) {
          return found[ref];
        }
        result = {};
        id = encoded['@id'];
        if (id) {
          found[id] = result;
        }
        for (key in encoded) {
          value = encoded[key];
          if (key !== '@id') {
            result[key] = doDecode(value);
          }
        }
        return result;
      };
      decodeArray = function(encoded) {
        var result, value, _i, _len;

        result = [];
        for (_i = 0, _len = encoded.length; _i < _len; _i++) {
          value = encoded[_i];
          result.push(decode(value));
        }
        return result;
      };
      if (Array.isArray(encoded)) {
        return decodeArray(encoded);
      } else if (typeof encoded === 'object') {
        return decodeObject(encoded);
      } else {
        return encoded;
      }
    };
    return doDecode(encoded);
  };

  JSOG.stringify = function(obj) {
    return JSON.stringify(JSOG.encode(obj));
  };

  JSOG.parse = function(str) {
    return JSOG.decode(JSON.parse(str));
  };

  if (module && module.exports) {
    module.exports = JSOG;
  }

  if (typeof window !== "undefined" && window !== null) {
    window.JSOG = JSOG;
  }

}).call(this);
